set(_CATKIN_CURRENT_PACKAGE "quad_gazebo")
set(quad_gazebo_VERSION "0.0.0")
set(quad_gazebo_MAINTAINER "wil <wil@wilselby.com>")
set(quad_gazebo_PACKAGE_FORMAT "1")
set(quad_gazebo_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(quad_gazebo_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(quad_gazebo_BUILDTOOL_DEPENDS "catkin")
set(quad_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(quad_gazebo_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(quad_gazebo_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(quad_gazebo_TEST_DEPENDS )
set(quad_gazebo_DOC_DEPENDS )
set(quad_gazebo_DEPRECATED "")